sudo: required
addons:
  apt:
    packages:
    - git
    - make
    - curl
env:
  - DOCKER_IMAGE_NAME=cloudposse/kube-ebs-snapshot

services:
- docker
install:
- make init
- make docker:login

script:
- make docker:build

after_success:
- make travis:docker-tag-and-push
